### ISSUE TITLE
New UI / UX designs

### ISSUE THREAD

**Issue by SaptakS** [kushaldas/tumpa#31]
Following are the design links for the new design mocks:

Available Keys: https://design.penpot.app/#/view/4f8eaf40-82b3-11eb-8f95-3363e266841f/7d5ac670-82b3-11eb-8ee5-6ba2e007e956?token=1IBT0bkuAce7UWeP7uRqHQ&index=0

Key Generation Form: https://design.penpot.app/#/view/4f8eaf40-82b3-11eb-8f95-3363e266841f/4cc42d80-82c7-11eb-8d47-5f1288a6bbce?token=xKbVsCDZEy1Fd391iqBcOw&index=0

Smart Card Options: https://design.penpot.app/#/view/4f8eaf40-82b3-11eb-8f95-3363e266841f/f286e2d0-8448-11eb-b38d-9b790b8d310b?index=0

There are many more elements/features needed to be added to the current design. We are currently working on implementing the above designs in the [ui-revamp](https://github.com/kushaldas/tumpa/tree/ui-revamp) branch

You can find discussions and issues related to the new UI implementation in #30 

If anyone is interested in helping us improve the designs, you will need to create an account in [penpot.app](https://penpot.app/) and then I can give you access to the designs. If you have used figma before, penpot is very similar to figma and is also open source.

**Comment by onaSousa** [comment]
Hello, I was interested in participating / helping. I am a web interface designer, I work with layout for web and desktop systems.

How would it be the best way to participate, would you start by discussing what you are already doing in issue # 30?

**Comment by SaptakS** [comment]
Hello @onaSousa! thanks for your interest in contributing. Right now, I think we are looking at validating that all the above designs make sense and if there is any improvement you think is needed from the UI/UX perspective.

Once the above is implemented, we will slowly start implementing the features mentioned [here](https://github.com/kushaldas/tumpa/wiki/Operations-we-want-to-do-via-this-tool) and will need design help for the same.

**Comment by onaSousa** [comment]
Nice @SaptakS 
I made some comments regarding the closed card, follow the link - https://design.penpot.app/#/view/80b9eab0-90cf-11eb-825c-a56ecc9e3fc1/80b9eab1-90cf-11eb-825c-a56ecc9e3fc1?token=PideSirvaPxlJVEYcinde 0

In my view the font size could increase 1px, it would help to improve the visualization;
I thought I could treat the month with the first 3 letters to avoid breaking that line;
And lastly I would propose to change the color of the arrow where it is clicked to the blue color, the same color that has on the main button

My eyes may be skewed because I am very used to websystems but in any case I would point this out on this card specifically
![image](https://user-images.githubusercontent.com/7890173/113065165-cc114700-918e-11eb-8db3-f5df17833d30.png)

**Comment by SaptakS** [comment]
Closing this in favor of https://github.com/kushaldas/tumpa/milestone/2
